# Generated by Django 3.2 on 2022-06-09 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20220507_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Reviews', 'Reviews'), ('Announcements', 'Announcements'), ('News', 'News'), ('Opinion', 'Opinion'), ('Previews', 'Previews'), ('Streaming', 'Streaming'), ('Tech', 'Tech'), ('Miscellaneous', 'Miscellaneous')], max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='blog_downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='blog_upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
