# Generated by Django 3.2 on 2022-06-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220609_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('R', 'Reviews'), ('A', 'Announcements'), ('N', 'News'), ('O', 'Opinion'), ('P', 'Previews'), ('S', 'Streaming'), ('T', 'Tech'), ('M', 'Miscellaneous')], max_length=30),
        ),
    ]
